let activeActionMenu = null;
let activeLocationId = null;

export function renderLocationSheet({ element, location, message = "", onClose, onAction, onOpenWorld = null }) {
  if (activeLocationId !== location.id) { activeLocationId = location.id; activeActionMenu = null; }
  const recruitActions = location.actions.filter((action) => action.id.startsWith("recruit:"));
  const depositResources = location.actions.filter((action) => action.id.startsWith("deposit-resource:"));
  const depositItems = location.actions.filter((action) => action.id.startsWith("deposit-item:"));
  const directActions = location.actions.filter((action) => !action.id.startsWith("recruit:") && !action.id.startsWith("deposit-"));
  const actionButtons = `${recruitActions.length ? '<button data-menu="recruit" type="button">Recruter</button>' : ""}${depositResources.length || depositItems.length ? '<button data-menu="deposit" type="button">Déposer</button>' : ""}${directActions.map((action) => `<button data-action="${action.id}" type="button">${action.label}</button>`).join("")}${onOpenWorld ? '<button class="secondary-button" data-open-world type="button">Voir la fiche complète</button>' : ""}`;
  const recruitMenu = `<div class="sheet-action-menu" data-sheet-menu="recruit" ${activeActionMenu === "recruit" ? "" : "hidden"}><button class="secondary-button sheet-menu-back" data-menu-back type="button">← Retour</button><h3>Recruter</h3>${recruitActions.map((action) => { const details = action.details ?? {}; const stats = details.stats ?? {}; const costs = Object.entries(details.costs ?? {}).filter(([, amount]) => amount > 0).map(([id, amount]) => `${amount} ${id}`).join(" · ") || "Gratuit"; return `<article class="recruit-option"><div><strong>${details.name ?? action.label}</strong><span>${details.available ?? 0} disponible(s)</span></div><p>ATQ ${stats.attack ?? "?"} · DÉF ${stats.defense ?? "?"} · VIT ${stats.speed ?? "?"} · POR ${stats.range ?? "?"} · MOR ${stats.morale ?? "?"}</p><footer><span>${costs}</span><button data-action="${action.id}" type="button">Recruter</button></footer></article>`; }).join("")}</div>`;
  const depositMenu = `<div class="sheet-action-menu" data-sheet-menu="deposit" ${activeActionMenu === "deposit" ? "" : "hidden"}><button class="secondary-button sheet-menu-back" data-menu-back type="button">← Retour</button><h3>Déposer</h3>${depositResources.map((action) => { const details = action.details ?? {}; const maximum = Math.floor(details.available ?? 0); return `<form class="deposit-resource" data-deposit-resource="${details.resourceName}"><label><span>${details.resourceName}</span><output>${maximum}</output><input type="range" min="0" max="${maximum}" value="${maximum}" step="1" /></label><button type="submit">Déposer</button></form>`; }).join("")}${depositItems.map((action) => `<button class="deposit-item-button secondary-button" data-action="${action.id}" type="button">${action.label}</button>`).join("")}</div>`;
  element.hidden = false;
  element.innerHTML = `<button class="sheet-close" type="button">Fermer</button><span class="sheet-state">${location.state}</span><h2>${location.name}</h2><p>${location.type} · ${Math.round(location.distance)} m</p><p>${location.description}</p>${message ? `<p class="sheet-feedback" role="status">${message}</p>` : ""}<div class="sheet-actions" ${activeActionMenu ? "hidden" : ""}>${location.nearby ? actionButtons : "Approchez-vous pour interagir."}</div>${location.nearby ? recruitMenu + depositMenu : ""}`;
  element.querySelector(".sheet-close").addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); activeActionMenu = null; onClose(); });
  element.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); onAction(button.dataset.action); }));
  element.querySelectorAll("[data-menu]").forEach((button) => button.addEventListener("click", () => { activeActionMenu = button.dataset.menu; element.querySelector(".sheet-actions").hidden = true; element.querySelector(`[data-sheet-menu="${activeActionMenu}"]`).hidden = false; }));
  element.querySelectorAll("[data-menu-back]").forEach((button) => button.addEventListener("click", () => { activeActionMenu = null; button.closest("[data-sheet-menu]").hidden = true; element.querySelector(".sheet-actions").hidden = false; }));
  element.querySelectorAll(".deposit-resource input").forEach((input) => input.addEventListener("input", () => { input.closest("label").querySelector("output").value = input.value; }));
  element.querySelectorAll("[data-deposit-resource]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const amount = Number(form.querySelector("input").value); if (amount > 0) onAction(`deposit-resource:${form.dataset.depositResource}:${amount}`); }));
  element.querySelector("[data-open-world]")?.addEventListener("click", () => onOpenWorld());
}

export function closeSheet(element) { element.hidden = true; element.innerHTML = ""; activeActionMenu = null; activeLocationId = null; }
