let activeActionMenu = null;
let activeLocationId = null;

export function renderLocationSheet({ element, location, message = "", onClose, onAction, onOpenWorld = null, onOpenGarrison = null }) {
  if (activeLocationId !== location.id) { activeLocationId = location.id; activeActionMenu = null; }
  const recruitActions = location.actions.filter((action) => action.id.startsWith("recruit:"));
  const depositResources = location.actions.filter((action) => action.id.startsWith("deposit-resource:"));
  const depositItems = location.actions.filter((action) => action.id.startsWith("deposit-item:"));
  const directActions = location.actions.filter((action) => !action.id.startsWith("recruit:") && !action.id.startsWith("deposit-"));
  const actionButtons = `${recruitActions.length ? '<button data-menu="recruit" type="button">Recruter</button>' : ""}${depositResources.length || depositItems.length ? '<button data-menu="deposit" type="button">Déposer</button>' : ""}${directActions.map((action) => `<button data-action="${action.id}" type="button">${action.label}</button>`).join("")}`;
  const recruitMenu = `<div class="sheet-action-menu" data-sheet-menu="recruit" ${activeActionMenu === "recruit" ? "" : "hidden"}><button class="secondary-button sheet-menu-back" data-menu-back type="button">← Retour</button><h3>Recruter</h3>${recruitActions.map((action) => { const details = action.details ?? {}; const stats = details.stats ?? {}; const costs = Object.entries(details.costs ?? {}).filter(([, amount]) => amount > 0).map(([id, amount]) => `${amount} ${id}`).join(" · ") || "Gratuit"; return `<article class="recruit-option"><div><strong>${details.name ?? action.label}</strong><span>${details.available ?? 0} disponible(s)</span></div><p>ATQ ${stats.attack ?? "?"} · DÉF ${stats.defense ?? "?"} · VIT ${stats.speed ?? "?"} · POR ${stats.range ?? "?"} · MOR ${stats.morale ?? "?"}</p><footer><span>${costs}</span><button data-action="${action.id}" type="button">Recruter</button></footer></article>`; }).join("")}</div>`;
  const depositMenu = `<div class="sheet-action-menu" data-sheet-menu="deposit" ${activeActionMenu === "deposit" ? "" : "hidden"}><button class="secondary-button sheet-menu-back" data-menu-back type="button">← Retour</button><h3>Déposer</h3>${depositResources.map((action) => { const details = action.details ?? {}; const maximum = Math.floor(details.available ?? 0); return `<form class="deposit-resource" data-deposit-resource="${details.resourceName}"><label><span>${details.resourceName}</span><output>${maximum}</output><input type="range" min="0" max="${maximum}" value="${maximum}" step="1" /></label><button type="submit">Déposer</button></form>`; }).join("")}${depositItems.map((action) => `<button class="deposit-item-button secondary-button" data-action="${action.id}" type="button">${action.label}</button>`).join("")}</div>`;
  element.hidden = false;
  element.innerHTML = `<button class="sheet-close" type="button">Fermer</button><span class="sheet-state">${location.state}</span><h2>${location.name}</h2><p>${location.type} · ${Math.round(location.distance)} m</p><p>${location.description}</p>${message ? `<p class="sheet-feedback" role="status">${message}</p>` : ""}<div class="sheet-actions" ${activeActionMenu ? "hidden" : ""}>${location.nearby ? actionButtons : "Approchez-vous pour interagir."}</div>${location.nearby ? recruitMenu + depositMenu : ""}`;
  if (recruitActions.length) { const details = recruitActions[0].details; const status = document.createElement("p"); status.className = `recruit-capacity${details.totalAvailable >= details.capacity ? " is-full" : ""}`; status.textContent = `Stock total : ${details.totalAvailable}/${details.capacity}${details.totalAvailable >= details.capacity ? " · capacité atteinte" : ""}`; element.querySelector('[data-sheet-menu="recruit"] h3')?.after(status); }
  element.querySelector(".sheet-close").addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); activeActionMenu = null; onClose(); });
  element.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); onAction(button.dataset.action); }));
  element.querySelectorAll("[data-menu]").forEach((button) => button.addEventListener("click", () => { activeActionMenu = button.dataset.menu; element.querySelector(".sheet-actions").hidden = true; element.querySelector(`[data-sheet-menu="${activeActionMenu}"]`).hidden = false; }));
  element.querySelectorAll("[data-menu-back]").forEach((button) => button.addEventListener("click", () => { activeActionMenu = null; button.closest("[data-sheet-menu]").hidden = true; element.querySelector(".sheet-actions").hidden = false; }));
  element.querySelectorAll(".deposit-resource input").forEach((input) => input.addEventListener("input", () => { input.closest("label").querySelector("output").value = input.value; }));
  element.querySelectorAll("[data-deposit-resource]").forEach((form) => form.addEventListener("submit", (event) => { event.preventDefault(); const amount = Number(form.querySelector("input").value); if (amount > 0) onAction(`deposit-resource:${form.dataset.depositResource}:${amount}`); }));
  const grab = document.createElement("div"); grab.className = "sheet-grab"; grab.tabIndex = 0; grab.setAttribute("role", "button"); grab.setAttribute("aria-label", "Ouvrir la fiche complète"); grab.innerHTML = "<i></i><span>⌃</span>"; element.prepend(grab);
  const defense = location.defense ?? { slots: 0, units: [], reinforcements: [] }; const slotCount = Number.isInteger(defense.slots) ? defense.slots : 0; const occupied = defense.units?.slice(0, slotCount) ?? []; const reinforcements = defense.reinforcements ?? [];
  { const summary = document.createElement("button"); summary.type = "button"; summary.className = "sheet-defense"; summary.disabled = !onOpenGarrison || !location.nearby || location.relation === "enemy" || slotCount === 0; summary.innerHTML = `<span><strong>Défense</strong><small>${occupied.length}/${slotCount} slots · ${reinforcements.length} renfort(s)</small></span><span class="sheet-defense-slots">${Array.from({ length: slotCount }, (_, index) => occupied[index] ? `<i class="is-occupied">⚔<small>${occupied[index].quantity}</small></i>` : "<i>＋</i>").join("") || "<em>Aucun slot</em>"}</span>${reinforcements.length ? `<span class="sheet-defense-reinforcements">${reinforcements.map((unit) => `<i>♟ ${unit.quantity} ${unit.name}${unit.heroName ? ` · ${unit.heroName}` : ""}</i>`).join("")}</span>` : ""}<small>${location.relation === "enemy" ? "Forces ennemies observées" : location.relation === "neutral" ? "Forces neutres observées" : location.nearby ? "Touchez pour gérer" : "Approchez-vous pour gérer"}</small>`; element.querySelector(".sheet-actions")?.before(summary); summary.addEventListener("click", () => onOpenGarrison?.()); }
  let startY = null; let openedByDrag = false; grab.addEventListener("pointerdown", (event) => { startY = event.clientY; grab.setPointerCapture(event.pointerId); event.preventDefault(); event.stopPropagation(); }); grab.addEventListener("pointerup", (event) => { openedByDrag = startY !== null && startY - event.clientY > 34; startY = null; event.preventDefault(); event.stopPropagation(); if (openedByDrag) onOpenWorld?.(); }); grab.addEventListener("click", (event) => { event.preventDefault(); event.stopPropagation(); if (!openedByDrag) onOpenWorld?.(); openedByDrag = false; }); grab.addEventListener("keydown", (event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onOpenWorld?.(); } });
  ["click", "pointerdown", "pointerup", "touchstart", "touchmove", "touchend"].forEach((type) => element.addEventListener(type, (event) => event.stopPropagation()));
}

export function closeSheet(element) { element.hidden = true; element.innerHTML = ""; element.classList.remove("garrison-sheet"); activeActionMenu = null; activeLocationId = null; }
