let filtersExpanded = false;

export function renderWorldDirectory({ element, locations, types = [], filters, onFilter, onOpen, onShowMap }) {
  const activeFilterCount = [filters.search, filters.type, filters.owner].filter(Boolean).length;
  element.innerHTML = `<section class="world-section"><div class="world-directory-heading"><h2>Annuaire du monde</h2><button class="world-filter-toggle secondary-button" type="button" data-toggle-filters aria-expanded="${filtersExpanded}" aria-controls="world-filters">⌕ Filtres${activeFilterCount ? ` (${activeFilterCount})` : ""}</button></div><div id="world-filters" class="world-filters" ${filtersExpanded ? "" : "hidden"}><label>Rechercher<input data-filter="search" type="search" value="${filters.search}" placeholder="Nom du lieu" /></label><label>Nature<select data-filter="type"><option value="">Toutes</option>${types.map((type) => `<option value="${type}" ${filters.type === type ? "selected" : ""}>${type}</option>`).join("")}</select></label><label>Propriétaire<select data-filter="owner"><option value="">Tous</option><option value="known" ${filters.owner === "known" ? "selected" : ""}>Connu</option><option value="unknown" ${filters.owner === "unknown" ? "selected" : ""}>Inconnu</option></select></label><label>Classement<select data-filter="sort"><option value="distance" ${filters.sort === "distance" ? "selected" : ""}>Distance</option><option value="name" ${filters.sort === "name" ? "selected" : ""}>Nom</option><option value="type" ${filters.sort === "type" ? "selected" : ""}>Nature</option><option value="owner" ${filters.sort === "owner" ? "selected" : ""}>Propriétaire</option></select></label></div><p class="text-muted">${locations.length} lieu(x) connu(s)</p><div class="world-grid">${locations.map(card).join("") || '<p class="world-empty">Aucun lieu ne correspond aux filtres.</p>'}</div></section>`;
  element.querySelector("[data-toggle-filters]").onclick = () => { filtersExpanded = !filtersExpanded; renderWorldDirectory({ element, locations, types, filters, onFilter, onOpen, onShowMap }); };
  element.querySelectorAll("[data-filter]").forEach((control) => control.oninput = () => onFilter(control.dataset.filter, control.value));
  element.querySelectorAll("[data-location-card]").forEach((cardElement) => cardElement.onclick = () => onOpen(cardElement.dataset.locationCard));
  element.querySelectorAll("[data-show-map]").forEach((button) => button.onclick = (event) => { event.stopPropagation(); onShowMap(button.dataset.showMap); });
}

export function renderLocationDetail({ element, location, index, total, message = "", onBack, onPrevious, onNext, onShowMap, onAction }) {
  const value = (input) => input === null || input === undefined || input === "" ? "inconnue" : input;
  const list = (items, render, empty = "Aucune information") => items.length ? `<ul>${items.map(render).join("")}</ul>` : `<p class="text-muted">${empty}</p>`;
  const resourceIds = [...new Set([...location.production.map((item) => item.id), ...location.stock.map((item) => item.id)])];
  const resources = list(resourceIds, (id) => { const productionEntry = location.production.find((item) => item.id === id); const stockEntry = location.stock.find((item) => item.id === id); const production = productionEntry?.amount; const stock = stockEntry?.amount ?? 0; const capacity = stockEntry?.capacity ?? productionEntry?.capacity ?? location.storageCapacity; return `<li><span>${id}${production === undefined ? "" : ` <small>(+${value(production)}/cycle)</small>`}</span><strong>${value(stock)}/${value(capacity)}</strong></li>`; }, "Aucune ressource connue");
  const presences = list(location.presences, (hero) => { const army = hero.army?.length ? ` · Armée : ${hero.army.map((unit) => `${unit.quantity} ${unit.type}`).join(", ")}` : ""; const stats = hero.stats.map((stat) => `${stat.id}: ${stat.assessment}${stat.value === null ? "" : ` (${stat.value})`}`).join(" · "); return `<li><span>${hero.label}</span><strong>${stats || "Présence détectée"}${army}</strong></li>`; }, "Aucun héros ennemi connu");
  const structures = list(location.defense.structures, (structure) => `<li><span>${structure.type}</span><strong>Niv. ${value(structure.level)}</strong></li>`, "Aucune structure défensive");
  element.innerHTML = `<section class="location-detail location-detail--compact">${message ? `<p class="sheet-feedback">${message}</p>` : ""}<div class="detail-nav"><button type="button" data-back>← Monde</button><span>${index + 1} / ${total}</span><button type="button" data-map>Afficher sur la carte</button></div><header><div class="location-heading"><div><p class="eyebrow">${location.nature} · information ${location.knowledgeLevel}/3</p><h2>${location.name}</h2></div><span>${Math.round(location.distance)} m</span></div><div class="location-header-facts"><span>Niv. <strong>${value(location.level)}</strong></span><span>Population <strong>${value(location.population)}</strong></span><span class="world-owner"><i style="--owner-color:${location.owner.color}"></i><strong>${location.owner.name}</strong></span></div><p>${location.description}</p></header><section class="location-actions"><h3>Actions</h3><div class="world-actions">${location.nearby ? location.actions.map((action) => `<button type="button" data-action="${action.id}">${action.label}</button>`).join("") || "Aucune action disponible." : `<span>Approchez à moins de ${Math.round(location.interactionRadius)} m pour interagir.</span>`}</div></section><section><h3>Ressources</h3>${resources}</section><section><h3>Présence et défense</h3>${presences}<h4>Structures défensives</h4>${structures}</section><footer class="detail-pager"><button type="button" data-previous ${index <= 0 ? "disabled" : ""}>← Lieu précédent</button><button type="button" data-next ${index >= total - 1 ? "disabled" : ""}>Lieu suivant →</button></footer></section>`;
  element.querySelector("[data-back]").onclick = onBack; element.querySelector("[data-map]").onclick = onShowMap; element.querySelector("[data-previous]").onclick = onPrevious; element.querySelector("[data-next]").onclick = onNext;
  element.querySelectorAll("[data-action]").forEach((button) => button.onclick = () => onAction(button.dataset.action));
}

function card(location) {
  const illustration = { fort: "♜", village: "⌂", mine: "◆", camp: "♨", quest: "✦" }[location.type] ?? "◇";
  const facts = [
    location.level !== null && location.level !== undefined ? `Niv. ${location.level}` : null,
    location.population !== null && location.population !== undefined ? `${location.population} hab.` : null,
  ].filter(Boolean).join(" · ");
  return `<article class="world-card" data-relation="${location.relation}" data-location-card="${location.id}"><div class="world-illustration" aria-hidden="true">${illustration}</div><div class="world-card__content"><div class="world-card__heading"><p class="eyebrow">${location.nature}</p><span class="world-distance">${Math.round(location.distance)} m</span></div><h3>${location.name}</h3><div class="world-card__meta"><p class="world-owner"><i style="--owner-color:${location.owner.color}"></i>${location.owner.name}</p>${facts ? `<span>${facts}</span>` : ""}</div></div><button type="button" class="world-map-button secondary-button" data-show-map="${location.id}" aria-label="Afficher ${location.name} sur la carte" title="Afficher sur la carte">⌖</button></article>`;
}
